/**
 * Metadado do banco geral — GERADO por `scripts/content/classify-legacy.ts`
 * (docs/30 §8.4/§18.2, Fase 3 T-3.4). Não editar à mão: rodar o script de
 * novo depois de mudar `src/data/questions.ts` ou a taxonomia.
 *
 * Heurístico (casamento de palavra-chave tópico↔habilidade, não leitura
 * manual item a item) — `validation.reviewer: "heuristica-topico"` marca
 * isso em cada entrada. 40 de 59 caíram no
 * fallback (nenhuma palavra em comum; usou a habilidade `core` da matéria).
 * Revisão humana real fica para quando o pipeline da Fase 9/11 tocar essas
 * questões, ou para uma passada dedicada — registrado em docs/32.
 */
import type { ItemMeta } from "../types";

export const ITEM_META_BANCO_GERAL: Record<string, ItemMeta> = {
  "q1": {
    id: "q1",
    version: 1,
    skillIds: ["mat:funcao-quadratica-vertice"],
    difficulty: 3,
    irt: { a: 1.0, b: 0, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 90,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "heuristica-topico" },
    examProfiles: ["enem"],
  },
  "q2": {
    id: "q2",
    version: 1,
    skillIds: ["mat:probabilidade-evento-simples"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 45,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "heuristica-topico" },
    examProfiles: ["enem"],
  },
  "q3": {
    id: "q3",
    version: 1,
    skillIds: ["por:sentido-figuras-linguagem"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 40,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "heuristica-topico" },
    examProfiles: ["enem"],
  },
  "q4": {
    id: "q4",
    version: 1,
    skillIds: ["fis:cinematica-movimento-uniforme"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 40,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q5": {
    id: "q5",
    version: 1,
    skillIds: ["qui:tabela-periodica-propriedades"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 30,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "heuristica-topico" },
    examProfiles: ["enem"],
  },
  "q6": {
    id: "q6",
    version: 1,
    skillIds: ["bio:membrana-estrutura"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 45,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q7": {
    id: "q7",
    version: 1,
    skillIds: ["his:era-vargas-politica-economia"],
    difficulty: 3,
    irt: { a: 1.0, b: 0, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 40,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "heuristica-topico" },
    examProfiles: ["enem"],
  },
  "q8": {
    id: "q8",
    version: 1,
    skillIds: ["geo:meio-ambiente-impactos"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 30,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q9": {
    id: "q9",
    version: 1,
    skillIds: ["ing:interpretacao-texto-curto"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 30,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q10": {
    id: "q10",
    version: 1,
    skillIds: ["mat:porcentagem-conceito"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 40,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "heuristica-topico" },
    examProfiles: ["enem"],
  },
  "q11": {
    id: "q11",
    version: 1,
    skillIds: ["mat:operacoes-fundamentais"],
    difficulty: 3,
    irt: { a: 1.0, b: 0, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 60,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q12": {
    id: "q12",
    version: 1,
    skillIds: ["por:crase-regra-basica"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 45,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "heuristica-topico" },
    examProfiles: ["enem"],
  },
  "q13": {
    id: "q13",
    version: 1,
    skillIds: ["fis:cinematica-movimento-uniforme"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 40,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q14": {
    id: "q14",
    version: 1,
    skillIds: ["qui:estrutura-atomica-modelos"],
    difficulty: 3,
    irt: { a: 1.0, b: 0, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 60,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q15": {
    id: "q15",
    version: 1,
    skillIds: ["bio:membrana-estrutura"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 45,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q16": {
    id: "q16",
    version: 1,
    skillIds: ["his:brasil-colonia-economia-sociedade"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 30,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "heuristica-topico" },
    examProfiles: ["enem"],
  },
  "q17": {
    id: "q17",
    version: 1,
    skillIds: ["geo:meio-ambiente-impactos"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 35,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q18": {
    id: "q18",
    version: 1,
    skillIds: ["fil:etica-correntes-filosoficas"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 25,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q19": {
    id: "q19",
    version: 1,
    skillIds: ["mat:operacoes-fundamentais"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 40,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q20": {
    id: "q20",
    version: 1,
    skillIds: ["ing:interpretacao-texto-curto"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 25,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q21": {
    id: "q21",
    version: 1,
    skillIds: ["mat:porcentagem-conceito"],
    difficulty: 3,
    irt: { a: 1.0, b: 0, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 70,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "heuristica-topico" },
    examProfiles: ["enem"],
  },
  "q22": {
    id: "q22",
    version: 1,
    skillIds: ["mat:operacoes-fundamentais"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 50,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q23": {
    id: "q23",
    version: 1,
    skillIds: ["mat:operacoes-fundamentais"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 45,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q24": {
    id: "q24",
    version: 1,
    skillIds: ["mat:operacoes-fundamentais"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 55,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q25": {
    id: "q25",
    version: 1,
    skillIds: ["mat:operacoes-fundamentais"],
    difficulty: 3,
    irt: { a: 1.0, b: 0, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 60,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q26": {
    id: "q26",
    version: 1,
    skillIds: ["mat:operacoes-fundamentais"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 40,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q27": {
    id: "q27",
    version: 1,
    skillIds: ["mat:operacoes-fundamentais"],
    difficulty: 3,
    irt: { a: 1.0, b: 0, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 65,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q28": {
    id: "q28",
    version: 1,
    skillIds: ["por:sentido-figuras-linguagem"],
    difficulty: 3,
    irt: { a: 1.0, b: 0, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 55,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "heuristica-topico" },
    examProfiles: ["enem"],
  },
  "q29": {
    id: "q29",
    version: 1,
    skillIds: ["por:concordancia-verbal-nominal"],
    difficulty: 3,
    irt: { a: 1.0, b: 0, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 60,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "heuristica-topico" },
    examProfiles: ["enem"],
  },
  "q30": {
    id: "q30",
    version: 1,
    skillIds: ["por:crase-regra-basica"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 50,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q31": {
    id: "q31",
    version: 1,
    skillIds: ["por:sentido-figuras-linguagem"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 45,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "heuristica-topico" },
    examProfiles: ["enem"],
  },
  "q32": {
    id: "q32",
    version: 1,
    skillIds: ["lit:modernismo-fases-brasil"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 50,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "heuristica-topico" },
    examProfiles: ["enem"],
  },
  "q33": {
    id: "q33",
    version: 1,
    skillIds: ["lit:caracteristicas-escolas-literarias"],
    difficulty: 3,
    irt: { a: 1.0, b: 0, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 60,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q34": {
    id: "q34",
    version: 1,
    skillIds: ["lit:caracteristicas-escolas-literarias"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 50,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q35": {
    id: "q35",
    version: 1,
    skillIds: ["fis:cinematica-movimento-uniforme"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 40,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q36": {
    id: "q36",
    version: 1,
    skillIds: ["fis:energia-trabalho-conservacao"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 45,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "heuristica-topico" },
    examProfiles: ["enem"],
  },
  "q37": {
    id: "q37",
    version: 1,
    skillIds: ["fis:cinematica-movimento-uniforme"],
    difficulty: 3,
    irt: { a: 1.0, b: 0, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 70,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q38": {
    id: "q38",
    version: 1,
    skillIds: ["fis:cinematica-movimento-uniforme"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 45,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q39": {
    id: "q39",
    version: 1,
    skillIds: ["fis:cinematica-movimento-uniforme"],
    difficulty: 3,
    irt: { a: 1.0, b: 0, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 60,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q40": {
    id: "q40",
    version: 1,
    skillIds: ["qui:estrutura-atomica-modelos"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 40,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q41": {
    id: "q41",
    version: 1,
    skillIds: ["qui:estrutura-atomica-modelos"],
    difficulty: 3,
    irt: { a: 1.0, b: 0, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 60,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q42": {
    id: "q42",
    version: 1,
    skillIds: ["qui:estrutura-atomica-modelos"],
    difficulty: 3,
    irt: { a: 1.0, b: 0, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 50,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q43": {
    id: "q43",
    version: 1,
    skillIds: ["qui:estrutura-atomica-modelos"],
    difficulty: 3,
    irt: { a: 1.0, b: 0, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 65,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q44": {
    id: "q44",
    version: 1,
    skillIds: ["bio:membrana-estrutura"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 40,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q45": {
    id: "q45",
    version: 1,
    skillIds: ["bio:membrana-estrutura"],
    difficulty: 3,
    irt: { a: 1.0, b: 0, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 60,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q46": {
    id: "q46",
    version: 1,
    skillIds: ["bio:membrana-estrutura"],
    difficulty: 3,
    irt: { a: 1.0, b: 0, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 55,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q47": {
    id: "q47",
    version: 1,
    skillIds: ["bio:membrana-estrutura"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 35,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q48": {
    id: "q48",
    version: 1,
    skillIds: ["his:ditadura-militar-contexto"],
    difficulty: 3,
    irt: { a: 1.0, b: 0, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 60,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "heuristica-topico" },
    examProfiles: ["enem"],
  },
  "q49": {
    id: "q49",
    version: 1,
    skillIds: ["his:guerra-fria-bipolaridade"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 50,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "heuristica-topico" },
    examProfiles: ["enem"],
  },
  "q50": {
    id: "q50",
    version: 1,
    skillIds: ["his:brasil-colonia-economia-sociedade"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 50,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "heuristica-topico" },
    examProfiles: ["enem"],
  },
  "q51": {
    id: "q51",
    version: 1,
    skillIds: ["geo:urbanizacao-processos"],
    difficulty: 3,
    irt: { a: 1.0, b: 0, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 60,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "heuristica-topico" },
    examProfiles: ["enem"],
  },
  "q52": {
    id: "q52",
    version: 1,
    skillIds: ["geo:meio-ambiente-impactos"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 50,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q53": {
    id: "q53",
    version: 1,
    skillIds: ["geo:meio-ambiente-impactos"],
    difficulty: 2,
    irt: { a: 1.0, b: -0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 45,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q54": {
    id: "q54",
    version: 1,
    skillIds: ["fil:etica-correntes-filosoficas"],
    difficulty: 3,
    irt: { a: 1.0, b: 0, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 55,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q55": {
    id: "q55",
    version: 1,
    skillIds: ["fil:etica-correntes-filosoficas"],
    difficulty: 4,
    irt: { a: 1.0, b: 0.8, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 70,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q56": {
    id: "q56",
    version: 1,
    skillIds: ["soc:desigualdade-social-estrutura"],
    difficulty: 3,
    irt: { a: 1.0, b: 0, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 65,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q57": {
    id: "q57",
    version: 1,
    skillIds: ["soc:desigualdade-social-estrutura"],
    difficulty: 3,
    irt: { a: 1.0, b: 0, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 60,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
  "q58": {
    id: "q58",
    version: 1,
    skillIds: ["ing:interpretacao-texto-curto"],
    difficulty: 3,
    irt: { a: 1.0, b: 0, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 55,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "heuristica-topico" },
    examProfiles: ["enem"],
  },
  "q59": {
    id: "q59",
    version: 1,
    skillIds: ["ing:interpretacao-texto-curto"],
    difficulty: 3,
    irt: { a: 1.0, b: 0, c: 0.20, source: "estimado" },
    roles: ["pratica", "revisao"],
    estimatedSeconds: 45,
    dontKnowAllowed: true,
    source: { kind: "autoral" },
    validation: { status: "revisada-humano", reviewer: "fallback-sem-palavra-chave" },
    examProfiles: ["enem"],
  },
};
