/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TrilhaRouteImport } from './routes/trilha'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as StudyRouteImport } from './routes/study'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as NivelamentoRouteImport } from './routes/nivelamento'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppRouteImport } from './routes/app'
import { Route as AhaRouteImport } from './routes/aha'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RedacaoIndexRouteImport } from './routes/redacao.index'
import { Route as VideoIdRouteImport } from './routes/video.$id'
import { Route as RedacaoLicaoIdRouteImport } from './routes/redacao.$licaoId'
import { Route as LearnLessonIdRouteImport } from './routes/learn.$lessonId'
import { Route as AtividadeActivityIdRouteImport } from './routes/atividade.$activityId'
import { Route as ApiSaudeRouteImport } from './routes/api/saude'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TrilhaRoute = TrilhaRouteImport.update({
  id: '/trilha',
  path: '/trilha',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const NivelamentoRoute = NivelamentoRouteImport.update({
  id: '/nivelamento',
  path: '/nivelamento',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AhaRoute = AhaRouteImport.update({
  id: '/aha',
  path: '/aha',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RedacaoIndexRoute = RedacaoIndexRouteImport.update({
  id: '/redacao/',
  path: '/redacao/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoIdRoute = VideoIdRouteImport.update({
  id: '/video/$id',
  path: '/video/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RedacaoLicaoIdRoute = RedacaoLicaoIdRouteImport.update({
  id: '/redacao/$licaoId',
  path: '/redacao/$licaoId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnLessonIdRoute = LearnLessonIdRouteImport.update({
  id: '/learn/$lessonId',
  path: '/learn/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadeActivityIdRoute = AtividadeActivityIdRouteImport.update({
  id: '/atividade/$activityId',
  path: '/atividade/$activityId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaudeRoute = ApiSaudeRouteImport.update({
  id: '/api/saude',
  path: '/api/saude',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aha': typeof AhaRoute
  '/app': typeof AppRoute
  '/dashboard': typeof DashboardRoute
  '/debug': typeof DebugRoute
  '/flashcards': typeof FlashcardsRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/nivelamento': typeof NivelamentoRoute
  '/offline': typeof OfflineRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/quiz': typeof QuizRoute
  '/ranking': typeof RankingRoute
  '/signup': typeof SignupRoute
  '/study': typeof StudyRoute
  '/topics': typeof TopicsRoute
  '/trilha': typeof TrilhaRoute
  '/welcome': typeof WelcomeRoute
  '/api/saude': typeof ApiSaudeRoute
  '/atividade/$activityId': typeof AtividadeActivityIdRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/redacao/$licaoId': typeof RedacaoLicaoIdRoute
  '/video/$id': typeof VideoIdRoute
  '/redacao/': typeof RedacaoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aha': typeof AhaRoute
  '/app': typeof AppRoute
  '/dashboard': typeof DashboardRoute
  '/debug': typeof DebugRoute
  '/flashcards': typeof FlashcardsRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/nivelamento': typeof NivelamentoRoute
  '/offline': typeof OfflineRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/quiz': typeof QuizRoute
  '/ranking': typeof RankingRoute
  '/signup': typeof SignupRoute
  '/study': typeof StudyRoute
  '/topics': typeof TopicsRoute
  '/trilha': typeof TrilhaRoute
  '/welcome': typeof WelcomeRoute
  '/api/saude': typeof ApiSaudeRoute
  '/atividade/$activityId': typeof AtividadeActivityIdRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/redacao/$licaoId': typeof RedacaoLicaoIdRoute
  '/video/$id': typeof VideoIdRoute
  '/redacao': typeof RedacaoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aha': typeof AhaRoute
  '/app': typeof AppRoute
  '/dashboard': typeof DashboardRoute
  '/debug': typeof DebugRoute
  '/flashcards': typeof FlashcardsRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/nivelamento': typeof NivelamentoRoute
  '/offline': typeof OfflineRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/quiz': typeof QuizRoute
  '/ranking': typeof RankingRoute
  '/signup': typeof SignupRoute
  '/study': typeof StudyRoute
  '/topics': typeof TopicsRoute
  '/trilha': typeof TrilhaRoute
  '/welcome': typeof WelcomeRoute
  '/api/saude': typeof ApiSaudeRoute
  '/atividade/$activityId': typeof AtividadeActivityIdRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/redacao/$licaoId': typeof RedacaoLicaoIdRoute
  '/video/$id': typeof VideoIdRoute
  '/redacao/': typeof RedacaoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aha'
    | '/app'
    | '/dashboard'
    | '/debug'
    | '/flashcards'
    | '/forgot'
    | '/login'
    | '/nivelamento'
    | '/offline'
    | '/onboarding'
    | '/plan'
    | '/premium'
    | '/profile'
    | '/progress'
    | '/quiz'
    | '/ranking'
    | '/signup'
    | '/study'
    | '/topics'
    | '/trilha'
    | '/welcome'
    | '/api/saude'
    | '/atividade/$activityId'
    | '/learn/$lessonId'
    | '/redacao/$licaoId'
    | '/video/$id'
    | '/redacao/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aha'
    | '/app'
    | '/dashboard'
    | '/debug'
    | '/flashcards'
    | '/forgot'
    | '/login'
    | '/nivelamento'
    | '/offline'
    | '/onboarding'
    | '/plan'
    | '/premium'
    | '/profile'
    | '/progress'
    | '/quiz'
    | '/ranking'
    | '/signup'
    | '/study'
    | '/topics'
    | '/trilha'
    | '/welcome'
    | '/api/saude'
    | '/atividade/$activityId'
    | '/learn/$lessonId'
    | '/redacao/$licaoId'
    | '/video/$id'
    | '/redacao'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/aha'
    | '/app'
    | '/dashboard'
    | '/debug'
    | '/flashcards'
    | '/forgot'
    | '/login'
    | '/nivelamento'
    | '/offline'
    | '/onboarding'
    | '/plan'
    | '/premium'
    | '/profile'
    | '/progress'
    | '/quiz'
    | '/ranking'
    | '/signup'
    | '/study'
    | '/topics'
    | '/trilha'
    | '/welcome'
    | '/api/saude'
    | '/atividade/$activityId'
    | '/learn/$lessonId'
    | '/redacao/$licaoId'
    | '/video/$id'
    | '/redacao/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AhaRoute: typeof AhaRoute
  AppRoute: typeof AppRoute
  DashboardRoute: typeof DashboardRoute
  DebugRoute: typeof DebugRoute
  FlashcardsRoute: typeof FlashcardsRoute
  ForgotRoute: typeof ForgotRoute
  LoginRoute: typeof LoginRoute
  NivelamentoRoute: typeof NivelamentoRoute
  OfflineRoute: typeof OfflineRoute
  OnboardingRoute: typeof OnboardingRoute
  PlanRoute: typeof PlanRoute
  PremiumRoute: typeof PremiumRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  QuizRoute: typeof QuizRoute
  RankingRoute: typeof RankingRoute
  SignupRoute: typeof SignupRoute
  StudyRoute: typeof StudyRoute
  TopicsRoute: typeof TopicsRoute
  TrilhaRoute: typeof TrilhaRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiSaudeRoute: typeof ApiSaudeRoute
  AtividadeActivityIdRoute: typeof AtividadeActivityIdRoute
  LearnLessonIdRoute: typeof LearnLessonIdRoute
  RedacaoLicaoIdRoute: typeof RedacaoLicaoIdRoute
  VideoIdRoute: typeof VideoIdRoute
  RedacaoIndexRoute: typeof RedacaoIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trilha': {
      id: '/trilha'
      path: '/trilha'
      fullPath: '/trilha'
      preLoaderRoute: typeof TrilhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nivelamento': {
      id: '/nivelamento'
      path: '/nivelamento'
      fullPath: '/nivelamento'
      preLoaderRoute: typeof NivelamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aha': {
      id: '/aha'
      path: '/aha'
      fullPath: '/aha'
      preLoaderRoute: typeof AhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redacao/': {
      id: '/redacao/'
      path: '/redacao'
      fullPath: '/redacao/'
      preLoaderRoute: typeof RedacaoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/$id': {
      id: '/video/$id'
      path: '/video/$id'
      fullPath: '/video/$id'
      preLoaderRoute: typeof VideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redacao/$licaoId': {
      id: '/redacao/$licaoId'
      path: '/redacao/$licaoId'
      fullPath: '/redacao/$licaoId'
      preLoaderRoute: typeof RedacaoLicaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$lessonId': {
      id: '/learn/$lessonId'
      path: '/learn/$lessonId'
      fullPath: '/learn/$lessonId'
      preLoaderRoute: typeof LearnLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividade/$activityId': {
      id: '/atividade/$activityId'
      path: '/atividade/$activityId'
      fullPath: '/atividade/$activityId'
      preLoaderRoute: typeof AtividadeActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/saude': {
      id: '/api/saude'
      path: '/api/saude'
      fullPath: '/api/saude'
      preLoaderRoute: typeof ApiSaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AhaRoute: AhaRoute,
  AppRoute: AppRoute,
  DashboardRoute: DashboardRoute,
  DebugRoute: DebugRoute,
  FlashcardsRoute: FlashcardsRoute,
  ForgotRoute: ForgotRoute,
  LoginRoute: LoginRoute,
  NivelamentoRoute: NivelamentoRoute,
  OfflineRoute: OfflineRoute,
  OnboardingRoute: OnboardingRoute,
  PlanRoute: PlanRoute,
  PremiumRoute: PremiumRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  QuizRoute: QuizRoute,
  RankingRoute: RankingRoute,
  SignupRoute: SignupRoute,
  StudyRoute: StudyRoute,
  TopicsRoute: TopicsRoute,
  TrilhaRoute: TrilhaRoute,
  WelcomeRoute: WelcomeRoute,
  ApiSaudeRoute: ApiSaudeRoute,
  AtividadeActivityIdRoute: AtividadeActivityIdRoute,
  LearnLessonIdRoute: LearnLessonIdRoute,
  RedacaoLicaoIdRoute: RedacaoLicaoIdRoute,
  VideoIdRoute: VideoIdRoute,
  RedacaoIndexRoute: RedacaoIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
