/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AhaRouteImport } from './routes/aha'
import { Route as AppRouteImport } from './routes/app'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CadernoRouteImport } from './routes/caderno'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as EsqueciASenhaRouteImport } from './routes/esqueci-a-senha'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as ImportarProgressoRouteImport } from './routes/importar-progresso'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as MissoesRouteImport } from './routes/missoes'
import { Route as NivelamentoRouteImport } from './routes/nivelamento'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PraticarRouteImport } from './routes/praticar'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RetrospectivaRouteImport } from './routes/retrospectiva'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StudyRouteImport } from './routes/study'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as TrilhaRouteImport } from './routes/trilha'
import { Route as VerificarEmailRouteImport } from './routes/verificar-email'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ApiSaudeRouteImport } from './routes/api/saude'
import { Route as AtividadeActivityIdRouteImport } from './routes/atividade.$activityId'
import { Route as CadastroCompletarRouteImport } from './routes/cadastro_.completar'
import { Route as LearnLessonIdRouteImport } from './routes/learn.$lessonId'
import { Route as PlanosRetornoRouteImport } from './routes/planos_.retorno'
import { Route as PraticarErrosRouteImport } from './routes/praticar_.erros'
import { Route as RedacaoIndexRouteImport } from './routes/redacao.index'
import { Route as RedacaoLicaoIdRouteImport } from './routes/redacao.$licaoId'
import { Route as RedacaoCorretorRouteImport } from './routes/redacao.corretor'
import { Route as RedacaoTreinoRouteImport } from './routes/redacao.treino'
import { Route as VideoIdRouteImport } from './routes/video.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronRetencaoRouteImport } from './routes/api/cron/retencao'
import { Route as ApiPagamentosWebhookRouteImport } from './routes/api/pagamentos/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AhaRoute = AhaRouteImport.update({
  id: '/aha',
  path: '/aha',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CadernoRoute = CadernoRouteImport.update({
  id: '/caderno',
  path: '/caderno',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciASenhaRoute = EsqueciASenhaRouteImport.update({
  id: '/esqueci-a-senha',
  path: '/esqueci-a-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarProgressoRoute = ImportarProgressoRouteImport.update({
  id: '/importar-progresso',
  path: '/importar-progresso',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const MissoesRoute = MissoesRouteImport.update({
  id: '/missoes',
  path: '/missoes',
  getParentRoute: () => rootRouteImport,
} as any)
const NivelamentoRoute = NivelamentoRouteImport.update({
  id: '/nivelamento',
  path: '/nivelamento',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PraticarRoute = PraticarRouteImport.update({
  id: '/praticar',
  path: '/praticar',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RetrospectivaRoute = RetrospectivaRouteImport.update({
  id: '/retrospectiva',
  path: '/retrospectiva',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const TrilhaRoute = TrilhaRouteImport.update({
  id: '/trilha',
  path: '/trilha',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificarEmailRoute = VerificarEmailRouteImport.update({
  id: '/verificar-email',
  path: '/verificar-email',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaudeRoute = ApiSaudeRouteImport.update({
  id: '/api/saude',
  path: '/api/saude',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadeActivityIdRoute = AtividadeActivityIdRouteImport.update({
  id: '/atividade/$activityId',
  path: '/atividade/$activityId',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroCompletarRoute = CadastroCompletarRouteImport.update({
  id: '/cadastro_/completar',
  path: '/cadastro/completar',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnLessonIdRoute = LearnLessonIdRouteImport.update({
  id: '/learn/$lessonId',
  path: '/learn/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRetornoRoute = PlanosRetornoRouteImport.update({
  id: '/planos_/retorno',
  path: '/planos/retorno',
  getParentRoute: () => rootRouteImport,
} as any)
const PraticarErrosRoute = PraticarErrosRouteImport.update({
  id: '/praticar_/erros',
  path: '/praticar/erros',
  getParentRoute: () => rootRouteImport,
} as any)
const RedacaoIndexRoute = RedacaoIndexRouteImport.update({
  id: '/redacao/',
  path: '/redacao/',
  getParentRoute: () => rootRouteImport,
} as any)
const RedacaoLicaoIdRoute = RedacaoLicaoIdRouteImport.update({
  id: '/redacao/$licaoId',
  path: '/redacao/$licaoId',
  getParentRoute: () => rootRouteImport,
} as any)
const RedacaoCorretorRoute = RedacaoCorretorRouteImport.update({
  id: '/redacao/corretor',
  path: '/redacao/corretor',
  getParentRoute: () => rootRouteImport,
} as any)
const RedacaoTreinoRoute = RedacaoTreinoRouteImport.update({
  id: '/redacao/treino',
  path: '/redacao/treino',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoIdRoute = VideoIdRouteImport.update({
  id: '/video/$id',
  path: '/video/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRetencaoRoute = ApiCronRetencaoRouteImport.update({
  id: '/api/cron/retencao',
  path: '/api/cron/retencao',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPagamentosWebhookRoute = ApiPagamentosWebhookRouteImport.update({
  id: '/api/pagamentos/webhook',
  path: '/api/pagamentos/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aha': typeof AhaRoute
  '/app': typeof AppRoute
  '/cadastro': typeof CadastroRoute
  '/caderno': typeof CadernoRoute
  '/dashboard': typeof DashboardRoute
  '/debug': typeof DebugRoute
  '/esqueci-a-senha': typeof EsqueciASenhaRoute
  '/flashcards': typeof FlashcardsRoute
  '/forgot': typeof ForgotRoute
  '/importar-progresso': typeof ImportarProgressoRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/missoes': typeof MissoesRoute
  '/nivelamento': typeof NivelamentoRoute
  '/offline': typeof OfflineRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/planos': typeof PlanosRoute
  '/praticar': typeof PraticarRoute
  '/premium': typeof PremiumRoute
  '/privacidade': typeof PrivacidadeRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/quiz': typeof QuizRoute
  '/ranking': typeof RankingRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/retrospectiva': typeof RetrospectivaRoute
  '/signup': typeof SignupRoute
  '/study': typeof StudyRoute
  '/termos': typeof TermosRoute
  '/topics': typeof TopicsRoute
  '/trilha': typeof TrilhaRoute
  '/verificar-email': typeof VerificarEmailRoute
  '/welcome': typeof WelcomeRoute
  '/api/saude': typeof ApiSaudeRoute
  '/atividade/$activityId': typeof AtividadeActivityIdRoute
  '/cadastro/completar': typeof CadastroCompletarRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/planos/retorno': typeof PlanosRetornoRoute
  '/praticar/erros': typeof PraticarErrosRoute
  '/redacao/$licaoId': typeof RedacaoLicaoIdRoute
  '/redacao/corretor': typeof RedacaoCorretorRoute
  '/redacao/treino': typeof RedacaoTreinoRoute
  '/video/$id': typeof VideoIdRoute
  '/redacao/': typeof RedacaoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/retencao': typeof ApiCronRetencaoRoute
  '/api/pagamentos/webhook': typeof ApiPagamentosWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aha': typeof AhaRoute
  '/app': typeof AppRoute
  '/cadastro': typeof CadastroRoute
  '/caderno': typeof CadernoRoute
  '/dashboard': typeof DashboardRoute
  '/debug': typeof DebugRoute
  '/esqueci-a-senha': typeof EsqueciASenhaRoute
  '/flashcards': typeof FlashcardsRoute
  '/forgot': typeof ForgotRoute
  '/importar-progresso': typeof ImportarProgressoRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/missoes': typeof MissoesRoute
  '/nivelamento': typeof NivelamentoRoute
  '/offline': typeof OfflineRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/planos': typeof PlanosRoute
  '/praticar': typeof PraticarRoute
  '/premium': typeof PremiumRoute
  '/privacidade': typeof PrivacidadeRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/quiz': typeof QuizRoute
  '/ranking': typeof RankingRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/retrospectiva': typeof RetrospectivaRoute
  '/signup': typeof SignupRoute
  '/study': typeof StudyRoute
  '/termos': typeof TermosRoute
  '/topics': typeof TopicsRoute
  '/trilha': typeof TrilhaRoute
  '/verificar-email': typeof VerificarEmailRoute
  '/welcome': typeof WelcomeRoute
  '/api/saude': typeof ApiSaudeRoute
  '/atividade/$activityId': typeof AtividadeActivityIdRoute
  '/cadastro/completar': typeof CadastroCompletarRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/planos/retorno': typeof PlanosRetornoRoute
  '/praticar/erros': typeof PraticarErrosRoute
  '/redacao/$licaoId': typeof RedacaoLicaoIdRoute
  '/redacao/corretor': typeof RedacaoCorretorRoute
  '/redacao/treino': typeof RedacaoTreinoRoute
  '/video/$id': typeof VideoIdRoute
  '/redacao': typeof RedacaoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/retencao': typeof ApiCronRetencaoRoute
  '/api/pagamentos/webhook': typeof ApiPagamentosWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aha': typeof AhaRoute
  '/app': typeof AppRoute
  '/cadastro': typeof CadastroRoute
  '/caderno': typeof CadernoRoute
  '/dashboard': typeof DashboardRoute
  '/debug': typeof DebugRoute
  '/esqueci-a-senha': typeof EsqueciASenhaRoute
  '/flashcards': typeof FlashcardsRoute
  '/forgot': typeof ForgotRoute
  '/importar-progresso': typeof ImportarProgressoRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/missoes': typeof MissoesRoute
  '/nivelamento': typeof NivelamentoRoute
  '/offline': typeof OfflineRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/planos': typeof PlanosRoute
  '/praticar': typeof PraticarRoute
  '/premium': typeof PremiumRoute
  '/privacidade': typeof PrivacidadeRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/quiz': typeof QuizRoute
  '/ranking': typeof RankingRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/retrospectiva': typeof RetrospectivaRoute
  '/signup': typeof SignupRoute
  '/study': typeof StudyRoute
  '/termos': typeof TermosRoute
  '/topics': typeof TopicsRoute
  '/trilha': typeof TrilhaRoute
  '/verificar-email': typeof VerificarEmailRoute
  '/welcome': typeof WelcomeRoute
  '/api/saude': typeof ApiSaudeRoute
  '/atividade/$activityId': typeof AtividadeActivityIdRoute
  '/cadastro_/completar': typeof CadastroCompletarRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/planos_/retorno': typeof PlanosRetornoRoute
  '/praticar_/erros': typeof PraticarErrosRoute
  '/redacao/$licaoId': typeof RedacaoLicaoIdRoute
  '/redacao/corretor': typeof RedacaoCorretorRoute
  '/redacao/treino': typeof RedacaoTreinoRoute
  '/video/$id': typeof VideoIdRoute
  '/redacao/': typeof RedacaoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/retencao': typeof ApiCronRetencaoRoute
  '/api/pagamentos/webhook': typeof ApiPagamentosWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aha'
    | '/app'
    | '/cadastro'
    | '/caderno'
    | '/dashboard'
    | '/debug'
    | '/esqueci-a-senha'
    | '/flashcards'
    | '/forgot'
    | '/importar-progresso'
    | '/login'
    | '/loja'
    | '/missoes'
    | '/nivelamento'
    | '/offline'
    | '/onboarding'
    | '/plan'
    | '/planos'
    | '/praticar'
    | '/premium'
    | '/privacidade'
    | '/profile'
    | '/progress'
    | '/quiz'
    | '/ranking'
    | '/redefinir-senha'
    | '/retrospectiva'
    | '/signup'
    | '/study'
    | '/termos'
    | '/topics'
    | '/trilha'
    | '/verificar-email'
    | '/welcome'
    | '/api/saude'
    | '/atividade/$activityId'
    | '/cadastro/completar'
    | '/learn/$lessonId'
    | '/planos/retorno'
    | '/praticar/erros'
    | '/redacao/$licaoId'
    | '/redacao/corretor'
    | '/redacao/treino'
    | '/video/$id'
    | '/redacao/'
    | '/api/auth/$'
    | '/api/cron/retencao'
    | '/api/pagamentos/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aha'
    | '/app'
    | '/cadastro'
    | '/caderno'
    | '/dashboard'
    | '/debug'
    | '/esqueci-a-senha'
    | '/flashcards'
    | '/forgot'
    | '/importar-progresso'
    | '/login'
    | '/loja'
    | '/missoes'
    | '/nivelamento'
    | '/offline'
    | '/onboarding'
    | '/plan'
    | '/planos'
    | '/praticar'
    | '/premium'
    | '/privacidade'
    | '/profile'
    | '/progress'
    | '/quiz'
    | '/ranking'
    | '/redefinir-senha'
    | '/retrospectiva'
    | '/signup'
    | '/study'
    | '/termos'
    | '/topics'
    | '/trilha'
    | '/verificar-email'
    | '/welcome'
    | '/api/saude'
    | '/atividade/$activityId'
    | '/cadastro/completar'
    | '/learn/$lessonId'
    | '/planos/retorno'
    | '/praticar/erros'
    | '/redacao/$licaoId'
    | '/redacao/corretor'
    | '/redacao/treino'
    | '/video/$id'
    | '/redacao'
    | '/api/auth/$'
    | '/api/cron/retencao'
    | '/api/pagamentos/webhook'
  id:
    | '__root__'
    | '/'
    | '/aha'
    | '/app'
    | '/cadastro'
    | '/caderno'
    | '/dashboard'
    | '/debug'
    | '/esqueci-a-senha'
    | '/flashcards'
    | '/forgot'
    | '/importar-progresso'
    | '/login'
    | '/loja'
    | '/missoes'
    | '/nivelamento'
    | '/offline'
    | '/onboarding'
    | '/plan'
    | '/planos'
    | '/praticar'
    | '/premium'
    | '/privacidade'
    | '/profile'
    | '/progress'
    | '/quiz'
    | '/ranking'
    | '/redefinir-senha'
    | '/retrospectiva'
    | '/signup'
    | '/study'
    | '/termos'
    | '/topics'
    | '/trilha'
    | '/verificar-email'
    | '/welcome'
    | '/api/saude'
    | '/atividade/$activityId'
    | '/cadastro_/completar'
    | '/learn/$lessonId'
    | '/planos_/retorno'
    | '/praticar_/erros'
    | '/redacao/$licaoId'
    | '/redacao/corretor'
    | '/redacao/treino'
    | '/video/$id'
    | '/redacao/'
    | '/api/auth/$'
    | '/api/cron/retencao'
    | '/api/pagamentos/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AhaRoute: typeof AhaRoute
  AppRoute: typeof AppRoute
  CadastroRoute: typeof CadastroRoute
  CadernoRoute: typeof CadernoRoute
  DashboardRoute: typeof DashboardRoute
  DebugRoute: typeof DebugRoute
  EsqueciASenhaRoute: typeof EsqueciASenhaRoute
  FlashcardsRoute: typeof FlashcardsRoute
  ForgotRoute: typeof ForgotRoute
  ImportarProgressoRoute: typeof ImportarProgressoRoute
  LoginRoute: typeof LoginRoute
  LojaRoute: typeof LojaRoute
  MissoesRoute: typeof MissoesRoute
  NivelamentoRoute: typeof NivelamentoRoute
  OfflineRoute: typeof OfflineRoute
  OnboardingRoute: typeof OnboardingRoute
  PlanRoute: typeof PlanRoute
  PlanosRoute: typeof PlanosRoute
  PraticarRoute: typeof PraticarRoute
  PremiumRoute: typeof PremiumRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  QuizRoute: typeof QuizRoute
  RankingRoute: typeof RankingRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  RetrospectivaRoute: typeof RetrospectivaRoute
  SignupRoute: typeof SignupRoute
  StudyRoute: typeof StudyRoute
  TermosRoute: typeof TermosRoute
  TopicsRoute: typeof TopicsRoute
  TrilhaRoute: typeof TrilhaRoute
  VerificarEmailRoute: typeof VerificarEmailRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiSaudeRoute: typeof ApiSaudeRoute
  AtividadeActivityIdRoute: typeof AtividadeActivityIdRoute
  CadastroCompletarRoute: typeof CadastroCompletarRoute
  LearnLessonIdRoute: typeof LearnLessonIdRoute
  PlanosRetornoRoute: typeof PlanosRetornoRoute
  PraticarErrosRoute: typeof PraticarErrosRoute
  RedacaoLicaoIdRoute: typeof RedacaoLicaoIdRoute
  RedacaoCorretorRoute: typeof RedacaoCorretorRoute
  RedacaoTreinoRoute: typeof RedacaoTreinoRoute
  VideoIdRoute: typeof VideoIdRoute
  RedacaoIndexRoute: typeof RedacaoIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronRetencaoRoute: typeof ApiCronRetencaoRoute
  ApiPagamentosWebhookRoute: typeof ApiPagamentosWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aha': {
      id: '/aha'
      path: '/aha'
      fullPath: '/aha'
      preLoaderRoute: typeof AhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caderno': {
      id: '/caderno'
      path: '/caderno'
      fullPath: '/caderno'
      preLoaderRoute: typeof CadernoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-a-senha': {
      id: '/esqueci-a-senha'
      path: '/esqueci-a-senha'
      fullPath: '/esqueci-a-senha'
      preLoaderRoute: typeof EsqueciASenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar-progresso': {
      id: '/importar-progresso'
      path: '/importar-progresso'
      fullPath: '/importar-progresso'
      preLoaderRoute: typeof ImportarProgressoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missoes': {
      id: '/missoes'
      path: '/missoes'
      fullPath: '/missoes'
      preLoaderRoute: typeof MissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nivelamento': {
      id: '/nivelamento'
      path: '/nivelamento'
      fullPath: '/nivelamento'
      preLoaderRoute: typeof NivelamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/praticar': {
      id: '/praticar'
      path: '/praticar'
      fullPath: '/praticar'
      preLoaderRoute: typeof PraticarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retrospectiva': {
      id: '/retrospectiva'
      path: '/retrospectiva'
      fullPath: '/retrospectiva'
      preLoaderRoute: typeof RetrospectivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trilha': {
      id: '/trilha'
      path: '/trilha'
      fullPath: '/trilha'
      preLoaderRoute: typeof TrilhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verificar-email': {
      id: '/verificar-email'
      path: '/verificar-email'
      fullPath: '/verificar-email'
      preLoaderRoute: typeof VerificarEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/saude': {
      id: '/api/saude'
      path: '/api/saude'
      fullPath: '/api/saude'
      preLoaderRoute: typeof ApiSaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividade/$activityId': {
      id: '/atividade/$activityId'
      path: '/atividade/$activityId'
      fullPath: '/atividade/$activityId'
      preLoaderRoute: typeof AtividadeActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro_/completar': {
      id: '/cadastro_/completar'
      path: '/cadastro/completar'
      fullPath: '/cadastro/completar'
      preLoaderRoute: typeof CadastroCompletarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$lessonId': {
      id: '/learn/$lessonId'
      path: '/learn/$lessonId'
      fullPath: '/learn/$lessonId'
      preLoaderRoute: typeof LearnLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos_/retorno': {
      id: '/planos_/retorno'
      path: '/planos/retorno'
      fullPath: '/planos/retorno'
      preLoaderRoute: typeof PlanosRetornoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/praticar_/erros': {
      id: '/praticar_/erros'
      path: '/praticar/erros'
      fullPath: '/praticar/erros'
      preLoaderRoute: typeof PraticarErrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redacao/': {
      id: '/redacao/'
      path: '/redacao'
      fullPath: '/redacao/'
      preLoaderRoute: typeof RedacaoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redacao/$licaoId': {
      id: '/redacao/$licaoId'
      path: '/redacao/$licaoId'
      fullPath: '/redacao/$licaoId'
      preLoaderRoute: typeof RedacaoLicaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redacao/corretor': {
      id: '/redacao/corretor'
      path: '/redacao/corretor'
      fullPath: '/redacao/corretor'
      preLoaderRoute: typeof RedacaoCorretorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redacao/treino': {
      id: '/redacao/treino'
      path: '/redacao/treino'
      fullPath: '/redacao/treino'
      preLoaderRoute: typeof RedacaoTreinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/$id': {
      id: '/video/$id'
      path: '/video/$id'
      fullPath: '/video/$id'
      preLoaderRoute: typeof VideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/retencao': {
      id: '/api/cron/retencao'
      path: '/api/cron/retencao'
      fullPath: '/api/cron/retencao'
      preLoaderRoute: typeof ApiCronRetencaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pagamentos/webhook': {
      id: '/api/pagamentos/webhook'
      path: '/api/pagamentos/webhook'
      fullPath: '/api/pagamentos/webhook'
      preLoaderRoute: typeof ApiPagamentosWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AhaRoute: AhaRoute,
  AppRoute: AppRoute,
  CadastroRoute: CadastroRoute,
  CadernoRoute: CadernoRoute,
  DashboardRoute: DashboardRoute,
  DebugRoute: DebugRoute,
  EsqueciASenhaRoute: EsqueciASenhaRoute,
  FlashcardsRoute: FlashcardsRoute,
  ForgotRoute: ForgotRoute,
  ImportarProgressoRoute: ImportarProgressoRoute,
  LoginRoute: LoginRoute,
  LojaRoute: LojaRoute,
  MissoesRoute: MissoesRoute,
  NivelamentoRoute: NivelamentoRoute,
  OfflineRoute: OfflineRoute,
  OnboardingRoute: OnboardingRoute,
  PlanRoute: PlanRoute,
  PlanosRoute: PlanosRoute,
  PraticarRoute: PraticarRoute,
  PremiumRoute: PremiumRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  QuizRoute: QuizRoute,
  RankingRoute: RankingRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  RetrospectivaRoute: RetrospectivaRoute,
  SignupRoute: SignupRoute,
  StudyRoute: StudyRoute,
  TermosRoute: TermosRoute,
  TopicsRoute: TopicsRoute,
  TrilhaRoute: TrilhaRoute,
  VerificarEmailRoute: VerificarEmailRoute,
  WelcomeRoute: WelcomeRoute,
  ApiSaudeRoute: ApiSaudeRoute,
  AtividadeActivityIdRoute: AtividadeActivityIdRoute,
  CadastroCompletarRoute: CadastroCompletarRoute,
  LearnLessonIdRoute: LearnLessonIdRoute,
  PlanosRetornoRoute: PlanosRetornoRoute,
  PraticarErrosRoute: PraticarErrosRoute,
  RedacaoLicaoIdRoute: RedacaoLicaoIdRoute,
  RedacaoCorretorRoute: RedacaoCorretorRoute,
  RedacaoTreinoRoute: RedacaoTreinoRoute,
  VideoIdRoute: VideoIdRoute,
  RedacaoIndexRoute: RedacaoIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronRetencaoRoute: ApiCronRetencaoRoute,
  ApiPagamentosWebhookRoute: ApiPagamentosWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
