import type { SkillDef } from "../types";

/**
 * Biologia (docs/30 §8, Fase 2). As 3 habilidades de citologia já existem
 * nas microlições (docs/25/26) — mesmos ids. As demais cobrem os tópicos de
 * maior incidência no ENEM (ecologia é praticamente garantida todo ano).
 */
export const SKILLS_BIO: SkillDef[] = [
  {
    id: "bio:membrana-estrutura",
    subjectId: "bio",
    topicId: "cit",
    area: "CN",
    name: "Descrever a estrutura da membrana plasmática (mosaico fluido)",
    prerequisites: [],
    core: true,
    incidence: 2,
    level: "base",
    status: "ativo",
  },
  {
    id: "bio:membrana-funcao",
    subjectId: "bio",
    topicId: "cit",
    area: "CN",
    name: "Explicar o transporte de substâncias através da membrana",
    prerequisites: ["bio:membrana-estrutura"],
    core: false,
    incidence: 2,
    level: "intermediario",
    status: "ativo",
  },
  {
    id: "bio:organelas-funcao",
    subjectId: "bio",
    topicId: "cit",
    area: "CN",
    name: "Relacionar cada organela citoplasmática à sua função",
    prerequisites: ["bio:membrana-estrutura"],
    core: false,
    incidence: 2,
    level: "intermediario",
    status: "ativo",
  },
  {
    id: "bio:genetica-leis-mendel",
    subjectId: "bio",
    topicId: "gen",
    area: "CN",
    name: "Resolver cruzamento genético com as leis de Mendel",
    prerequisites: [],
    core: true,
    incidence: 3,
    level: "intermediario",
    status: "ativo",
  },
  {
    id: "bio:evolucao-selecao-natural",
    subjectId: "bio",
    topicId: "evo",
    area: "CN",
    name: "Explicar um fenômeno evolutivo pela seleção natural",
    prerequisites: [],
    core: false,
    incidence: 2,
    level: "intermediario",
    status: "ativo",
  },
  {
    id: "bio:ecologia-relacoes-ecossistema",
    subjectId: "bio",
    topicId: "eco",
    area: "CN",
    name: "Identificar relações ecológicas e fluxo de energia num ecossistema",
    prerequisites: [],
    core: true,
    incidence: 3,
    level: "base",
    status: "ativo",
  },
  {
    id: "bio:fisiologia-humana-sistemas",
    subjectId: "bio",
    topicId: "fis",
    area: "CN",
    name: "Relacionar órgão e função num sistema do corpo humano",
    prerequisites: [],
    core: false,
    incidence: 2,
    level: "base",
    status: "ativo",
  },
];
