import type { SkillDef } from "../types";

/**
 * Matemática (docs/30 §8, Fase 2 T-2.3/T-2.4). As 3 habilidades de
 * porcentagem já existem nas microlições (docs/25/26) — mesmos ids, sem
 * alteração. As demais cobrem os 14 tópicos de `SUBJECTS.mat` com foco nos
 * fundamentos de maior incidência no ENEM (função, geometria, estatística,
 * probabilidade — a prova pesa nisso todo ano).
 */
export const SKILLS_MAT: SkillDef[] = [
  // --- Aritmética / razão / porcentagem ---
  {
    id: "mat:operacoes-fundamentais",
    subjectId: "mat",
    topicId: "arit",
    area: "MT",
    name: "Resolver expressões numéricas com as quatro operações e potenciação",
    prerequisites: [],
    core: true,
    incidence: 2,
    level: "base",
    status: "ativo",
  },
  {
    id: "mat:razao-proporcao",
    subjectId: "mat",
    topicId: "razao",
    area: "MT",
    name: "Resolver problema com razão, proporção e regra de três simples",
    prerequisites: ["mat:operacoes-fundamentais"],
    core: true,
    incidence: 3,
    level: "base",
    status: "ativo",
  },
  {
    id: "mat:porcentagem-conceito",
    subjectId: "mat",
    topicId: "porc",
    area: "MT",
    name: "Entender porcentagem como fração de 100",
    prerequisites: ["mat:razao-proporcao"],
    core: true,
    incidence: 3,
    level: "base",
    status: "ativo",
  },
  {
    id: "mat:porcentagem-valor",
    subjectId: "mat",
    topicId: "porc",
    area: "MT",
    name: "Calcular X% de um valor",
    prerequisites: ["mat:porcentagem-conceito"],
    core: true,
    incidence: 3,
    level: "base",
    status: "ativo",
  },
  {
    id: "mat:porcentagem-fator-multiplicativo",
    subjectId: "mat",
    topicId: "porc",
    area: "MT",
    name: "Aplicar fator multiplicativo em aumento e desconto percentual",
    prerequisites: ["mat:porcentagem-valor"],
    core: false,
    incidence: 3,
    level: "intermediario",
    status: "ativo",
  },
  // --- Equações e funções ---
  {
    id: "mat:equacao-primeiro-grau",
    subjectId: "mat",
    topicId: "eq",
    area: "MT",
    name: "Resolver equação do primeiro grau com uma incógnita",
    prerequisites: ["mat:operacoes-fundamentais"],
    core: true,
    incidence: 2,
    level: "base",
    status: "ativo",
  },
  {
    id: "mat:funcao-afim-grafico",
    subjectId: "mat",
    topicId: "f1",
    area: "MT",
    name: "Interpretar o gráfico e a lei de uma função do primeiro grau",
    prerequisites: ["mat:equacao-primeiro-grau"],
    core: true,
    incidence: 3,
    level: "intermediario",
    status: "ativo",
  },
  {
    id: "mat:funcao-quadratica-vertice",
    subjectId: "mat",
    topicId: "f2",
    area: "MT",
    name: "Encontrar o vértice e as raízes de uma função do segundo grau",
    prerequisites: ["mat:funcao-afim-grafico"],
    core: false,
    incidence: 2,
    level: "intermediario",
    status: "ativo",
  },
  {
    id: "mat:funcao-exponencial-crescimento",
    subjectId: "mat",
    topicId: "fexp",
    area: "MT",
    name: "Modelar crescimento ou decaimento exponencial num contexto",
    prerequisites: ["mat:funcao-afim-grafico", "mat:porcentagem-fator-multiplicativo"],
    core: false,
    incidence: 2,
    level: "avancado",
    status: "ativo",
  },
  {
    id: "mat:logaritmo-propriedades",
    subjectId: "mat",
    topicId: "log",
    area: "MT",
    name: "Aplicar propriedades de logaritmo para resolver equação exponencial",
    prerequisites: ["mat:funcao-exponencial-crescimento"],
    core: false,
    incidence: 1,
    level: "avancado",
    status: "planejado",
  },
  // --- Geometria e trigonometria ---
  {
    id: "mat:area-perimetro-figuras-planas",
    subjectId: "mat",
    topicId: "geoplana",
    area: "MT",
    name: "Calcular área e perímetro de figuras planas compostas",
    prerequisites: ["mat:operacoes-fundamentais"],
    core: true,
    incidence: 3,
    level: "base",
    status: "ativo",
  },
  {
    id: "mat:volume-solidos-geometricos",
    subjectId: "mat",
    topicId: "geoesp",
    area: "MT",
    name: "Calcular volume de prismas, cilindros e outros sólidos",
    prerequisites: ["mat:area-perimetro-figuras-planas"],
    core: false,
    incidence: 2,
    level: "intermediario",
    status: "ativo",
  },
  {
    id: "mat:trigonometria-triangulo-retangulo",
    subjectId: "mat",
    topicId: "trig",
    area: "MT",
    name: "Usar seno, cosseno e tangente para achar lado ou ângulo",
    prerequisites: ["mat:area-perimetro-figuras-planas"],
    core: false,
    incidence: 2,
    level: "intermediario",
    status: "ativo",
  },
  // --- Estatística, probabilidade e combinatória ---
  {
    id: "mat:leitura-grafico-tabela",
    subjectId: "mat",
    topicId: "estat",
    area: "MT",
    name: "Ler e comparar dados apresentados em gráfico ou tabela",
    prerequisites: [],
    core: true,
    incidence: 3,
    level: "base",
    status: "ativo",
  },
  {
    id: "mat:media-mediana-moda",
    subjectId: "mat",
    topicId: "estat",
    area: "MT",
    name: "Calcular média, mediana e moda de um conjunto de dados",
    prerequisites: ["mat:leitura-grafico-tabela"],
    core: true,
    incidence: 3,
    level: "base",
    status: "ativo",
  },
  {
    id: "mat:probabilidade-evento-simples",
    subjectId: "mat",
    topicId: "prob",
    area: "MT",
    name: "Calcular a probabilidade de um evento simples",
    prerequisites: ["mat:razao-proporcao"],
    core: true,
    incidence: 3,
    level: "intermediario",
    status: "ativo",
  },
  {
    id: "mat:analise-combinatoria-contagem",
    subjectId: "mat",
    topicId: "comb",
    area: "MT",
    name: "Contar agrupamentos com o princípio multiplicativo",
    prerequisites: ["mat:probabilidade-evento-simples"],
    core: false,
    incidence: 2,
    level: "avancado",
    status: "planejado",
  },
];
