import type { SkillDef } from "../types";

/**
 * Português (docs/30 §8, Fase 2). As 2 habilidades de crase já existem nas
 * microlições (docs/25/26) — mesmos ids. As demais derivam das 11 outras
 * trilhas legadas de Português (docs/30 §12.3, "Português/Redação: derivar
 * das 15 trilhas legadas"), uma habilidade representativa por trilha — o
 * detalhamento fino de cada trilha em habilidades menores fica para quando
 * o conteúdo legado for reclassificado item a item (Fase 3, F3.5).
 */
export const SKILLS_POR: SkillDef[] = [
  {
    id: "por:crase-regra-basica",
    subjectId: "por",
    topicId: "crase",
    area: "LC",
    name: "Aplicar a regra geral de crase (a + a = à)",
    prerequisites: [],
    core: true,
    incidence: 3,
    level: "base",
    status: "ativo",
  },
  {
    id: "por:crase-casos-proibidos",
    subjectId: "por",
    topicId: "crase",
    area: "LC",
    name: "Reconhecer os casos em que a crase é proibida",
    prerequisites: ["por:crase-regra-basica"],
    core: false,
    incidence: 3,
    level: "intermediario",
    status: "ativo",
  },
  {
    id: "por:concordancia-verbal-nominal",
    subjectId: "por",
    topicId: "conc",
    area: "LC",
    name: "Aplicar concordância verbal e nominal em casos do dia a dia da prova",
    prerequisites: [],
    core: true,
    incidence: 3,
    level: "base",
    status: "ativo",
  },
  {
    id: "por:regencia-verbal-nominal",
    subjectId: "por",
    topicId: "reg",
    area: "LC",
    name: "Identificar a regência correta de verbos e nomes comuns na prova",
    prerequisites: [],
    core: false,
    incidence: 2,
    level: "intermediario",
    status: "ativo",
  },
  {
    id: "por:pontuacao-virgula-regras",
    subjectId: "por",
    topicId: "pont",
    area: "LC",
    name: "Decidir onde a vírgula é obrigatória, proibida ou opcional",
    prerequisites: [],
    core: true,
    incidence: 3,
    level: "base",
    status: "ativo",
  },
  {
    id: "por:ortografia-acentuacao",
    subjectId: "por",
    topicId: "orto",
    area: "LC",
    name: "Aplicar as regras de acentuação gráfica",
    prerequisites: [],
    core: true,
    incidence: 2,
    level: "base",
    status: "ativo",
  },
  {
    id: "por:classes-gramaticais-identificacao",
    subjectId: "por",
    topicId: "classes",
    area: "LC",
    name: "Identificar a classe gramatical de uma palavra pelo contexto",
    prerequisites: [],
    core: true,
    incidence: 2,
    level: "base",
    status: "ativo",
  },
  {
    id: "por:tempos-verbais-emprego",
    subjectId: "por",
    topicId: "gram",
    area: "LC",
    name: "Empregar o tempo e o modo verbal adequados ao contexto",
    prerequisites: ["por:classes-gramaticais-identificacao"],
    core: false,
    incidence: 2,
    level: "intermediario",
    status: "ativo",
  },
  {
    id: "por:formacao-palavras-processos",
    subjectId: "por",
    topicId: "classes",
    area: "LC",
    name: "Reconhecer processos de formação de palavras (derivação, composição)",
    prerequisites: ["por:classes-gramaticais-identificacao"],
    core: false,
    incidence: 1,
    level: "intermediario",
    status: "ativo",
  },
  {
    id: "por:sintaxe-termos-oracao",
    subjectId: "por",
    topicId: "gram",
    area: "LC",
    name: "Identificar sujeito, predicado e complementos de uma oração",
    prerequisites: ["por:classes-gramaticais-identificacao"],
    core: true,
    incidence: 2,
    level: "intermediario",
    status: "ativo",
  },
  {
    id: "por:sintaxe-periodo-composto",
    subjectId: "por",
    topicId: "gram",
    area: "LC",
    name: "Classificar orações coordenadas e subordinadas num período composto",
    prerequisites: ["por:sintaxe-termos-oracao"],
    core: false,
    incidence: 2,
    level: "avancado",
    status: "ativo",
  },
  {
    id: "por:sentido-figuras-linguagem",
    subjectId: "por",
    topicId: "fig",
    area: "LC",
    name: "Reconhecer figuras de linguagem e seu efeito de sentido no texto",
    prerequisites: [],
    core: false,
    incidence: 2,
    level: "intermediario",
    status: "ativo",
  },
  {
    id: "por:interpretacao-ideia-principal",
    subjectId: "por",
    topicId: "interp",
    area: "LC",
    name: "Identificar a ideia principal e a intenção de um texto",
    prerequisites: [],
    core: true,
    incidence: 3,
    level: "base",
    status: "ativo",
  },
];
